name: Flutter Weekly Build

on:
  schedule:
    # schedule build every Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  run-flutter-weekly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "weekly"
